### ISSUE TITLE
Vamos controlar quem acessa qual relatório? Ou vamos deixar isso a cargo da aplicação que estiver chamando?

### ISSUE THREAD

**Issue by viniciusss** [sonny-blaine/reimagined-reports#1]

**Comment by millerp** [comment]
Cada aplicação deveria ter controle de quem acessa os relatórios, se não teríamos que ter mais uma camada na nossa aplicação e não é isso que queremos, queremos somente entregar os relatórios, independente de quem esta solicitando.

**Comment by RafagaQueiroz** [comment]
Se não houver controle na aplicação, pessoas má intencionadas podem obter os dados, não?

**Comment by basilioferraz** [comment]
Então, acredito que a aplicação que estiver solicitando o relatório deve controlar isso, podemos ter algum tipo de autenticação aqui não sei.

**Comment by carlosrodriguesf** [comment]
Concordo com o @basilioferraz . Acho que poderia ser gerado um token pra evitar que qualquer um acesse o relatório, mas uma vez que a aplicação tiver o token, a responsabilidade de gerenciar os usuários que têm ou não acesso ao mesmo fica a cargo dela.

**Comment by viniciusss** [comment]
Foi definido que iremos gerar um token por relatório.
