### ISSUE TITLE
tudo que é relacionado a view será feito em javascript?

### ISSUE THREAD

**Issue by viniciusss** [sonny-blaine/reimagined-reports#2]

**Comment by carlosrodriguesf** [comment]
Eu acho interessante, principalmente se for usar React, Vue ou algum framework front-end do tipo. Assim no back-end a gente vai ter basicamente uma api, se algum dia precisar utilizar só os dados em algum outro projeto já ta pronto. Se fosse o caso podia usar o twig pra gerar só o html das tabelas se fosse necessário ou mais cômodo, como seria no webpdv, receber os dados em uma table já pronta pra ser injetada em alguma div, sendo necessário apenas passar um parâmetro pra API pra receber um html ou um json.

**Comment by viniciusss** [comment]
O html virá do backend.
