### ISSUE TITLE
Vamos utilizar algum framework?

### ISSUE THREAD

**Issue by viniciusss** [sonny-blaine/reimagined-reports#3]

**Comment by cesarAugusto1994** [comment]
Seria bom utilizar um que já tenhamos familiaridade como por exemplo o Silex, acho que ele atenderia para resolver esse quetão.

**Comment by carlosrodriguesf** [comment]
Acho que isso é meio relativo. As vezes seria bom, até mesmo pra gente, utilizar algo novo justamente pra gente não ficar preso na mesma coisa sempre, mas aí vai depender da necessidade também, as vezes framework x vai atender melhor que o framework y. Mas por fora acho que seria interessante usar:

 - Algum microframework pra tratar as rotas (Silex/Slim?)
 - Twig pra renderizar os templates (vai ter?)
 - Doctrine pra comunicar com o banco (talvez nem seja necessário, qual vai ser o banco? mysql mesmo?)
 - Algum container de injeção de dependências(Pimple?)
 - Alguma biblioteca front-end React
   - bootstrap(só os css's)
   - React & React Router

Acho que esses podem ser muito úteis pro projeto, mas é aquele negócio, vai depender da necessidade.

**Comment by viniciusss** [comment]
Vamos utilizar Silex e desenvolver os agents com nodejs.
