### ISSUE TITLE
Poderemos ter vários tipos de Source? Será que conseguimos aproveitar algo do Integrator?

### ISSUE THREAD

**Issue by viniciusss** [sonny-blaine/reimagined-reports#4]

**Comment by RafagaQueiroz** [comment]
O integrador atualmente trabalha com queries prontas, apesar de poder ter conexões diferentes. Como faríamos?

**Comment by basilioferraz** [comment]
Pensei o mesmo que o Ráfaga, como faríamos?  Qual seria o papel dele?  _O integrador é uma ferramenta voltada para outro tipo de negócio acredito eu._

**Comment by cesarAugusto1994** [comment]
To por fora, O que seria esse integrador?

**Comment by basilioferraz** [comment]
Falar do _Integrador_ assim por texto é meio complicado kkkk. Na quinta-feira podemos trocar uma idéia a respeito dele.
https://github.com/sonny-blaine/integrator

**Comment by cesarAugusto1994** [comment]
Esta bem.

**Comment by viniciusss** [comment]
Vamos ter vários sources, mas vamos usar os próprios agents.
