### ISSUE TITLE
As views serão geradas por essa ferramenta? Teremos que criar algum tipo de cadastro de templates?

### ISSUE THREAD

**Issue by viniciusss** [sonny-blaine/reimagined-reports#5]

**Comment by basilioferraz** [comment]
Acho esse negócio de templates complicado, pensando em (WebPdv) temos diversos relatórios com templates diferentes, no meu ver seria selecionar uns 3 mais utilizados e deixar cadastrado,  no meu ver se deixar um cadastro de templates vai acabar deixando o usuário muito solto, apenas opinião minha.

**Comment by cesarAugusto1994** [comment]
Não seria melhor retirar a responsabilidade do webpdv de gerar ou apenas requisitar os relatório e utilizar uma farramenta (aplicação) à parte que seria reponsável únicamente por gerar relatórios?, Um WebPDV-Relatórios.

**Comment by basilioferraz** [comment]
Acredito que para os novos seria uma boa @cesarAugusto1994 , se for um negócio muito bem feito acredito que da certo.

**Comment by viniciusss** [comment]
Vamos usar bootstrap, com geração apenas de tabelas em html, pdf e excel.
